title:
  en: "OSCP - Offensive Sec Certified Professional"
  es: "OSCP - Offensive Sec Certified Professional"

description:
  en: >
      Validates expertise in using the Elastic Stack for security monitoring and analysis. Covers Stack architecture, Fleet and Elastic Agents, and applying ECS. Includes creating visualizations and dashboards for security use cases, using the Security App to monitor events, analyze alerts, correlate data, and track incidents.

  es: >
    Valida experiencia en el uso de Elastic Stack para monitorización y análisis de seguridad. Cubre arquitectura del Stack, Fleet y Elastic Agents, y aplicación del (ECS). Incluye creación de visualizaciones y dashboards para usar la Security App para monitorizar eventos, analizar alertas, correlacionar datos y seguir incidentes. 

img: "https://templates.images.credential.net/17363044335833111771106241425275.png"
link: "https://www.elastic.co/training/elastic-certified-siem-analyst-exam"
date: "COMING SOON"
order: 3
blocked: true