import { TAGS } from "./tags";

export const TECH_STACK = [
    {
        title: "techstack-frontend",
        used_tech: [
            TAGS.HTML,
            TAGS.CSS,
            TAGS.JavaScript,
            TAGS.Typescript,
            TAGS.React,
            TAGS.Astro,
            TAGS.Angular,
            TAGS.SocketIo,
            TAGS.TailwindCSS,
            TAGS.Android,
        ],
    },
    {
        title: "techstack-backend",
        used_tech: [
            TAGS.NodeJs,
            TAGS.Java,
            TAGS.PostgreSQL,
            TAGS.SQLite,
            TAGS.SocketIo,
        ],
    },
    {
        title: "techstack-cloud",
        used_tech: [
            TAGS.AWS,
            TAGS.GoogleCloud,
            TAGS.Azure,
            TAGS.Docker,
            TAGS.Kubernetes,
            TAGS.Golang,
            TAGS.Bash,
            TAGS.Apache,
            TAGS.Nginx,
        ],
        double: true,
    },
    {
        title: "techstack-others",
        used_tech: [
            TAGS.Cplusplus,
            TAGS.Python,
            TAGS.NumPy,
            TAGS.Pandas,
            TAGS.Java,
            TAGS.Golang,
            TAGS.Haskell,
            TAGS.Assembly,
            TAGS.AxureRP,
            TAGS.Bash,
            TAGS.Apache,
            TAGS.Nginx,
            TAGS.Docker,
            TAGS.Kubernetes,
            TAGS.STM32,
        ],
        double: true,
    },
];